name: Discord notifications

on: [push, pull_request_target]

jobs:
  notify_discord:
    runs-on: ubuntu-20.04
    if: always() && (github.event_name == 'pull_request_target' || (github.event_name == 'push'))
    #if: always() && github.repository == 'SerenityOS/serenity' && (github.event_name == 'pull_request_target' || (github.event_name == 'push' && github.ref == 'refs/heads/master'))
    #extra

    steps:
      - name: Wait for tests to finish
        uses: IdanHo/action-wait-for-check@890bf0671eeeac09faf19f57deb4397eeccc59aa
        id: wait-for-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          excludedCheckName: "notify_discord"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 100

      - name: Discord action notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_EVENT_NAME: ${{ (github.event_name == 'pull_request_target' && "pull_request" || github.event_name ) }} # fake the event type as discord doesnt know how to parse the special pull_request_target context
        uses: Ilshidur/action-discord@0.3.0
        if: ${{ (github.event['pull_request'] && github.event['action'] == 'opened' && !(github.event['pull_request'] == 'draft')) || github.event['commits'] }}

      - name: Discord build status
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub # we have to set these manually for non-default messages
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        uses: Ilshidur/action-discord@0.3.0
        if: ${{ (github.event['pull_request'] && github.event['action'] == 'opened' && !(github.event['pull_request'] == 'draft')) || github.event['commits'] }}
        with:
          args: "The build ${{ steps.wait-for-tests.outputs.conclusion == 'success' && 'passed :white_check_mark:' || 'failed :x:' }}"
